language: en
dictionaries: ["nl-nl"]
ignorePaths:
  # Ignore GIMP files
  - "**/*.xcf"
  # Ignore License files that should not be touched
  - "LICENSE"
  - "LICENSES/*"
import:
  - "@cspell/dict-nl-nl/cspell-ext.json"
